<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0B8xjEr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0B8xjEr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0B8xjEr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0B8xjEr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0B8xjEr\App_KernelDevDebugContainer([
    'container.build_hash' => '0B8xjEr',
    'container.build_id' => 'e4f9fa19',
    'container.build_time' => 1591776878,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0B8xjEr');
